name: Convert VMR Excel

on:
  push:
    paths:
      - 'VMR.xlsx'

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref_name }}
        fetch-depth: 0

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install system dependencies for lxml
      run: |
        sudo apt-get update
        sudo apt-get install -y libxml2-dev libxslt1-dev python3-dev

    - name: Upgrade pip and install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Convert VMR.xlsx to TSV, JSON, XML
      run: python convert-vmr.py

    - name: Commit and push converted files
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add converted_files/
        git commit -m "Auto-convert VMR.xlsx to TSV, JSON, XML"
        git push origin ${{ github.ref_name }}
      continue-on-error: true
