name: Convert VMR Excel

on:
  push:
    paths:
      - 'VMR.xlsx'

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Convert VMR.xlsx to TSV, JSON, XML
      run: python convert.py

    - name: Commit and push converted files
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add converted_files/
        git commit -m "Auto-convert VMR.xlsx to TSV, JSON, XML"
        git push
      # If no changes, commit will fail — ignore error
      continue-on-error: true
