name: Fetch Taxon IDs

on:
  workflow_dispatch:  # You can also use "push" or a schedule

jobs:
  fetch-taxids:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install biopython requests

    - name: Run Taxon Fetch Script
      env:
        ENTREZ_EMAIL: your_email@example.com  # Or use secrets
      run: |
        python scripts/fetch_taxids.py

    - name: Upload result artifact
      uses: actions/upload-artifact@v4
      with:
        name: accession_to_taxid
        path: accession_to_taxid.json
