name: Merge ICTV JSON files

on:
  workflow_dispatch:  # manual trigger
  schedule:
    - cron: '0 0 * * 1'  # every Monday at midnight UTC

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install requests

    - name: Run merge script
      run: python 0_merge_ictv_files.py

    - name: List files in converted_files for debug
      run: ls -l converted_files

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add converted_files/merged_ictv.json
        if ! git diff --quiet || ! git diff --staged --quiet; then
          git commit -m "Auto-update merged ICTV JSON"
          git push
        else
          echo "No changes to commit"
        fi
